export const regions = [
  { id: 'all', label: 'Barcha mintaqalar' },
  { id: 'Europe', label: 'Yevropa' },
  { id: 'Asia-Pacific', label: 'Osiyo–Tinch okeani' },
  { id: 'Americas', label: 'Amerika' },
  { id: 'Middle East', label: 'Yaqin Sharq' },
  { id: 'Africa', label: 'Afrika' },
  { id: 'Central Asia', label: 'Markaziy Osiyo' },
];

export const regionStats = [
  { name: 'Yevropa', value: 793, growth: '+4%', color: '#df6a3f' },
  { name: 'Osiyo–Tinch okeani', value: 331, growth: '+6%', color: '#d8a33d' },
  { name: 'Amerika', value: 218, growth: '+1%', color: '#377a70' },
  { name: 'Yaqin Sharq', value: 100, growth: '+3%', color: '#7a7c44' },
  { name: 'Afrika', value: 81, growth: '+8%', color: '#9b5745' },
];

export const timeline = [
  { year: 2019, value: 1465 },
  { year: 2020, value: 406 },
  { year: 2021, value: 456 },
  { year: 2022, value: 963 },
  { year: 2023, value: 1300 },
  { year: 2024, value: 1462 },
  { year: 2025, value: 1520 },
];

export const countries = [
  {
    code: 'FR', flag: '🇫🇷', name: 'Fransiya', region: 'Europe', capital: 'Parij', arrivals: 100.0,
    dishes: ['baget', 'pishloq', 'kruassan', 'coq au vin'],
    heritage: 'Fransuzlarning gastronomik taomi — UNESCO nomoddiy merosi',
    tourism: 'Parij, Luara vodiysi, Provans, Bordo va Alp tog‘lari',
    story: 'Terroir tamoyili mahsulotning ta’mi, kelib chiqishi va hududiy identitetini bir tizimda bog‘laydi.',
    best: 'aprel–iyun, sentabr–oktabr', budget: 'high', style: ['culture', 'wine', 'luxury'],
    metrics: { H: 98, T: 96, X: 97, S: 78, A: 94, L: 90, D: 96 },
  },
  {
    code: 'ES', flag: '🇪🇸', name: 'Ispaniya', region: 'Europe', capital: 'Madrid', arrivals: 93.8,
    dishes: ['paella', 'tapas', 'jamón', 'gazpacho'],
    heritage: 'O‘rta yer dengizi parhezi — ko‘p mamlakatli UNESCO merosi',
    tourism: 'Barselona, Andalusiya, Madrid, Basklar yurti va orollar',
    story: 'Tapas madaniyati birgalikda ovqatlanish, shahar makoni va kichik bizneslarni gastronomik tajribaga aylantiradi.',
    best: 'mart–iyun, sentabr–noyabr', budget: 'mid', style: ['culture', 'sea', 'night'],
    metrics: { H: 96, T: 95, X: 96, S: 76, A: 95, L: 92, D: 95 },
  },
  {
    code: 'US', flag: '🇺🇸', name: 'AQSh', region: 'Americas', capital: 'Vashington', arrivals: 72.4,
    dishes: ['barbekyu', 'burger', 'Cajun', 'farm-to-table'],
    heritage: 'Ko‘p madaniyatli oshxona va hududiy foodscape modeli',
    tourism: 'Nyu-York, Kaliforniya, milliy bog‘lar, Yangi Orlean',
    story: 'Immigratsiya oqimlari, innovatsion restoran bozori va yirik festival iqtisodiyoti gastronomik xilma-xillikni kuchaytiradi.',
    best: 'aprel–iyun, sentabr–oktabr', budget: 'high', style: ['urban', 'nature', 'innovation'],
    metrics: { H: 82, T: 92, X: 91, S: 72, A: 93, L: 78, D: 94 },
  },
  {
    code: 'TR', flag: '🇹🇷', name: 'Turkiya', region: 'Middle East', capital: 'Anqara', arrivals: 60.6,
    dishes: ['kabob', 'baklava', 'meze', 'turk qahvasi'],
    heritage: 'Turk qahvasi madaniyati — UNESCO nomoddiy merosi',
    tourism: 'Istanbul, Kapadokiya, Antaliya, Gaziantep va Egey sohili',
    story: 'Anadolu, Usmonli va O‘rta yer dengizi qatlamlari bozor, ko‘cha taomi va saroy oshxonasini tutashtiradi.',
    best: 'aprel–iyun, sentabr–oktabr', budget: 'mid', style: ['culture', 'market', 'sea'],
    metrics: { H: 96, T: 91, X: 94, S: 73, A: 89, L: 93, D: 91 },
  },
  {
    code: 'IT', flag: '🇮🇹', name: 'Italiya', region: 'Europe', capital: 'Rim', arrivals: 57.7,
    dishes: ['pasta', 'pizza', 'risotto', 'gelato'],
    heritage: 'Neapolitan pizzaiuolo san’ati — UNESCO nomoddiy merosi',
    tourism: 'Rim, Toskana, Sitsiliya, Neapol va Emiliya-Romanya',
    story: 'Kuchli regionalizm, qisqa qiymat zanjiri va mavsumiy mahsulotlar Italiya gastronomiyasining asosiy kapitalidir.',
    best: 'aprel–iyun, sentabr–oktabr', budget: 'mid', style: ['culture', 'wine', 'slow'],
    metrics: { H: 99, T: 91, X: 98, S: 80, A: 91, L: 95, D: 93 },
  },
  {
    code: 'MX', flag: '🇲🇽', name: 'Meksika', region: 'Americas', capital: 'Mexiko', arrivals: 45.0,
    dishes: ['taco', 'mole', 'tamale', 'pozole'],
    heritage: 'An’anaviy Meksika oshxonasi — UNESCO nomoddiy merosi',
    tourism: 'Mexiko, Oaxaka, Yukatan, Puebla va Tinch okeani sohili',
    story: 'Makkajo‘xori, loviya va chili asosidagi tirik meros mahalliy jamoalar bilimini turizm qiymat zanjiriga olib kiradi.',
    best: 'noyabr–aprel', budget: 'mid', style: ['culture', 'street', 'sea'],
    metrics: { H: 98, T: 85, X: 95, S: 70, A: 82, L: 94, D: 88 },
  },
  {
    code: 'GB', flag: '🇬🇧', name: 'Buyuk Britaniya', region: 'Europe', capital: 'London', arrivals: 41.2,
    dishes: ['fish & chips', 'Sunday roast', 'cheddar', 'afternoon tea'],
    heritage: 'Pub, bozor va zamonaviy ko‘p madaniyatli restoran ekotizimi',
    tourism: 'London, Edinburg, Kornuoll, Kotsuolds va York',
    story: 'An’anaviy mahsulotlar va global diaspora oshxonalari zamonaviy shahar foodscape’larini yaratadi.',
    best: 'may–sentabr', budget: 'high', style: ['urban', 'culture', 'festival'],
    metrics: { H: 84, T: 89, X: 87, S: 78, A: 92, L: 82, D: 89 },
  },
  {
    code: 'DE', flag: '🇩🇪', name: 'Germaniya', region: 'Europe', capital: 'Berlin', arrivals: 37.5,
    dishes: ['bratwurst', 'pretzel', 'sauerkraut', 'non mahsulotlari'],
    heritage: 'Hududiy non, pivo va mavsumiy yarmarka madaniyati',
    tourism: 'Berlin, Bavariya, Reyn vodiysi, Gamburg va Qora o‘rmon',
    story: 'Standartlashtirish, hunarmandchilik va festival logistikasi gastronomik mahsulotni yil davomida sotishga imkon beradi.',
    best: 'may–oktabr, dekabr', budget: 'high', style: ['festival', 'urban', 'nature'],
    metrics: { H: 85, T: 87, X: 84, S: 86, A: 94, L: 86, D: 87 },
  },
  {
    code: 'JP', flag: '🇯🇵', name: 'Yaponiya', region: 'Asia-Pacific', capital: 'Tokio', arrivals: 36.9,
    dishes: ['sushi', 'ramen', 'kaiseki', 'tempura'],
    heritage: 'Washoku — UNESCO nomoddiy merosi',
    tourism: 'Tokio, Kioto, Osaka, Hokkaydo va Setouti',
    story: 'Mavsumiylik, minimalizm, omotenashi va yuqori xizmat intizomi taomni yaxlit estetik tajribaga aylantiradi.',
    best: 'mart–may, oktyabr–noyabr', budget: 'high', style: ['culture', 'innovation', 'slow'],
    metrics: { H: 98, T: 88, X: 99, S: 84, A: 95, L: 94, D: 94 },
  },
  {
    code: 'GR', flag: '🇬🇷', name: 'Gretsiya', region: 'Europe', capital: 'Afina', arrivals: 35.9,
    dishes: ['moussaka', 'souvlaki', 'feta', 'zaytun'],
    heritage: 'O‘rta yer dengizi parhezi va simpozium an’analari',
    tourism: 'Afina, Krit, Saloniki, Santorini va Peloponnes',
    story: 'Orol va tog‘ xo‘jaliklari, zaytun moyi va mehmondo‘stlik gastronomik tajribaning hududiy asosini yaratadi.',
    best: 'aprel–iyun, sentabr–oktabr', budget: 'mid', style: ['sea', 'slow', 'culture'],
    metrics: { H: 94, T: 86, X: 90, S: 77, A: 87, L: 91, D: 88 },
  },
  {
    code: 'TH', flag: '🇹🇭', name: 'Tailand', region: 'Asia-Pacific', capital: 'Bangkok', arrivals: 35.5,
    dishes: ['pad thai', 'tom yum', 'som tam', 'yashil karri'],
    heritage: 'Tomyum Kung — UNESCO nomoddiy merosi',
    tourism: 'Bangkok, Chiang May, Phuket, Krabi va Isan',
    story: 'Ko‘cha taomlari, bozorlardagi tezkor aylanish va aromatik muvozanat Tailand brendining asosiy kuchidir.',
    best: 'noyabr–fevral', budget: 'low', style: ['street', 'sea', 'wellness'],
    metrics: { H: 91, T: 86, X: 96, S: 70, A: 88, L: 92, D: 91 },
  },
  {
    code: 'AT', flag: '🇦🇹', name: 'Avstriya', region: 'Europe', capital: 'Vena', arrivals: 32.2,
    dishes: ['schnitzel', 'sachertorte', 'strudel', 'qahva'],
    heritage: 'Vena qahvaxonasi va Alp fermer xo‘jaliklari an’anasi',
    tourism: 'Vena, Salzburg, Tirol, Graz va Dunay vodiysi',
    story: 'Imperiya merosi, musiqa va qahvaxona instituti gastronomiyani madaniy turizm bilan birlashtiradi.',
    best: 'may–sentabr, dekabr', budget: 'high', style: ['culture', 'mountain', 'luxury'],
    metrics: { H: 88, T: 84, X: 86, S: 88, A: 95, L: 87, D: 84 },
  },
  {
    code: 'SA', flag: '🇸🇦', name: 'Saudiya Arabistoni', region: 'Middle East', capital: 'Ar-Riyod', arrivals: 29.7,
    dishes: ['kabsa', 'jareesh', 'xurmo', 'arab qahvasi'],
    heritage: 'Arab qahvasi — saxovat ramzi sifatidagi UNESCO merosi',
    tourism: 'Al-Ula, Jidda, Ar-Riyod, Asir va Qizil dengiz',
    story: 'Meros hududlari, yangi transport infratuzilmasi va festival investitsiyalari bozorni tez sur’atda shakllantirmoqda.',
    best: 'oktyabr–mart', budget: 'high', style: ['heritage', 'desert', 'luxury'],
    metrics: { H: 87, T: 81, X: 82, S: 68, A: 88, L: 82, D: 87 },
  },
  {
    code: 'PT', flag: '🇵🇹', name: 'Portugaliya', region: 'Europe', capital: 'Lissabon', arrivals: 29.0,
    dishes: ['bacalhau', 'pastel de nata', 'sardina', 'cataplana'],
    heritage: 'Atlantika dengiz mahsulotlari va O‘rta yer dengizi parhezi',
    tourism: 'Lissabon, Portu, Douro, Algarve va Madeyra',
    story: 'Dengizchilik tarixi, sharob yo‘llari va mahalliy bozorlar ixcham, yuqori qiymatli marshrutlar yaratadi.',
    best: 'mart–iyun, sentabr–noyabr', budget: 'mid', style: ['sea', 'wine', 'slow'],
    metrics: { H: 91, T: 82, X: 91, S: 81, A: 89, L: 90, D: 85 },
  },
  {
    code: 'MY', flag: '🇲🇾', name: 'Malayziya', region: 'Asia-Pacific', capital: 'Kuala-Lumpur', arrivals: 25.0,
    dishes: ['nasi lemak', 'laksa', 'satay', 'roti canai'],
    heritage: 'Malay, xitoy va hind oshxonalarining ko‘p qatlamli uyg‘unligi',
    tourism: 'Kuala-Lumpur, Penang, Malakka, Sabah va Langkavi',
    story: 'Hawker markazlari va ko‘p etnik oshxona nisbatan arzon narxda yuqori xilma-xillik beradi.',
    best: 'dekabr–mart, iyun–avgust', budget: 'low', style: ['street', 'nature', 'urban'],
    metrics: { H: 89, T: 78, X: 93, S: 72, A: 88, L: 90, D: 83 },
  },
  {
    code: 'VN', flag: '🇻🇳', name: 'Vyetnam', region: 'Asia-Pacific', capital: 'Xanoy', arrivals: 17.6,
    dishes: ['pho', 'banh mi', 'bun cha', 'cao lau'],
    heritage: 'Ko‘cha oshxonasi va yangi mahsulotlar muvozanati',
    tourism: 'Xanoy, Xoshimin, Xoyan, Hue va Mekong deltasi',
    story: 'Mintaqaviy farqlar, bozor tarmoqlari va kundalik oshxona sayyohga autentik hamda ishtirokchi tajriba beradi.',
    best: 'fevral–aprel, avgust–oktabr', budget: 'low', style: ['street', 'culture', 'nature'],
    metrics: { H: 90, T: 73, X: 94, S: 72, A: 79, L: 92, D: 82 },
  },
  {
    code: 'MA', flag: '🇲🇦', name: 'Marokash', region: 'Africa', capital: 'Rabot', arrivals: 17.4,
    dishes: ['tajin', 'kuskus', 'pastilla', 'yalpizli choy'],
    heritage: 'Kuskus va O‘rta yer dengizi parhezi — UNESCO merosi',
    tourism: 'Marrakesh, Fes, Atlas, Essaouira va Sahroi Kabir',
    story: 'Suk bozorlari, ziravorlar va oilaviy riadlar gastronomiyani hunarmandchilik hamda me’moriy meros bilan bog‘laydi.',
    best: 'mart–may, sentabr–noyabr', budget: 'mid', style: ['market', 'desert', 'culture'],
    metrics: { H: 95, T: 74, X: 93, S: 71, A: 82, L: 94, D: 84 },
  },
  {
    code: 'SG', flag: '🇸🇬', name: 'Singapur', region: 'Asia-Pacific', capital: 'Singapur', arrivals: 16.5,
    dishes: ['chili crab', 'Hainan rice', 'laksa', 'kaya toast'],
    heritage: 'Hawker madaniyati — UNESCO nomoddiy merosi',
    tourism: 'Hawker markazlari, Marina Bay, Sentosa va etnik kvartallar',
    story: 'Sanitariya, logistika va etnik xilma-xillik ko‘cha taomini global darajadagi boshqariladigan tajribaga aylantiradi.',
    best: 'fevral–aprel, iyul–sentabr', budget: 'high', style: ['street', 'urban', 'innovation'],
    metrics: { H: 87, T: 74, X: 95, S: 86, A: 98, L: 85, D: 86 },
  },
  {
    code: 'KR', flag: '🇰🇷', name: 'Janubiy Koreya', region: 'Asia-Pacific', capital: 'Seul', arrivals: 16.4,
    dishes: ['kimchi', 'bibimbap', 'bulgogi', 'tteokbokki'],
    heritage: 'Kimjang — kimchi tayyorlash va ulashish UNESCO merosi',
    tourism: 'Seul, Jeonju, Busan, Jeju va Andong',
    story: 'K-content, tungi bozorlar va fermentatsiya merosi gastronomik brendni raqamli platformalarda tez yoyadi.',
    best: 'aprel–may, sentabr–noyabr', budget: 'mid', style: ['urban', 'culture', 'innovation'],
    metrics: { H: 92, T: 73, X: 94, S: 82, A: 94, L: 88, D: 88 },
  },
  {
    code: 'UZ', flag: '🇺🇿', name: 'O‘zbekiston', region: 'Central Asia', capital: 'Toshkent', arrivals: 10.2,
    dishes: ['palov', 'samsa', 'non', 'shashlik'],
    heritage: 'Palov madaniyati va an’anasi — UNESCO nomoddiy merosi',
    tourism: 'Samarqand, Buxoro, Xiva, Toshkent va Farg‘ona vodiysi',
    story: 'Buyuk Ipak yo‘li, mahalla mehmondo‘stligi va bozorlar gastronomik turizmni hududiy rivojlanish drayveriga aylantira oladi.',
    best: 'aprel–may, sentabr–oktabr', budget: 'low', style: ['heritage', 'market', 'culture'],
    metrics: { H: 96, T: 62, X: 91, S: 75, A: 70, L: 93, D: 76 },
  },
  {
    code: 'IN', flag: '🇮🇳', name: 'Hindiston', region: 'Asia-Pacific', capital: 'Nyu-Dehli', arrivals: 9.9,
    dishes: ['biryani', 'dosa', 'thali', 'chaat'],
    heritage: 'Ziravor, diniy amaliyot va hududiy oshxonalarning ulkan tizimi',
    tourism: 'Dehli, Rajastan, Kerala, Goa, Lakhnau va Varanasi',
    story: 'Vegetarian an’analar, ko‘cha taomlari va erta shakllangan ziravor yo‘llari nihoyatda boy gastronomik geografiyani yaratadi.',
    best: 'oktyabr–mart', budget: 'low', style: ['culture', 'street', 'wellness'],
    metrics: { H: 98, T: 61, X: 96, S: 68, A: 72, L: 95, D: 80 },
  },
  {
    code: 'ZA', flag: '🇿🇦', name: 'Janubiy Afrika', region: 'Africa', capital: 'Pretoriya', arrivals: 8.9,
    dishes: ['braai', 'bobotie', 'bunny chow', 'Cape wine'],
    heritage: 'Mahalliy, malay va yevropa oshxonalari chorrahasi',
    tourism: 'Keyptaun, Winelands, Durban, Kruger va Garden Route',
    story: 'Sharob yo‘llari, safari va ko‘p madaniyatli shahar taomlari uzoq turishli kombinatsion marshrutlarni qo‘llab-quvvatlaydi.',
    best: 'mart–may, sentabr–noyabr', budget: 'mid', style: ['nature', 'wine', 'adventure'],
    metrics: { H: 84, T: 58, X: 87, S: 76, A: 75, L: 84, D: 73 },
  },
  {
    code: 'AU', flag: '🇦🇺', name: 'Avstraliya', region: 'Asia-Pacific', capital: 'Kanberra', arrivals: 8.3,
    dishes: ['native bush food', 'seafood', 'barbekyu', 'flat white'],
    heritage: 'Mahalliy First Nations bilimlari va zamonaviy fusion oshxonasi',
    tourism: 'Sidney, Melburn, Tasmaniya, Buyuk to‘siq rifi va sharob vodiylari',
    story: 'Bioxilma-xillik, kuchli xavfsizlik standartlari va migrant oshxonalari premium tajriba yaratadi.',
    best: 'sentabr–noyabr, mart–may', budget: 'high', style: ['nature', 'wine', 'innovation'],
    metrics: { H: 82, T: 56, X: 89, S: 89, A: 90, L: 84, D: 79 },
  },
  {
    code: 'GE', flag: '🇬🇪', name: 'Gruziya', region: 'Central Asia', capital: 'Tbilisi', arrivals: 7.4,
    dishes: ['khachapuri', 'khinkali', 'qvevri sharobi', 'lobio'],
    heritage: 'Qvevri sharob tayyorlash usuli — UNESCO nomoddiy merosi',
    tourism: 'Tbilisi, Kaxeti, Kazbegi, Svaneti va Batumi',
    story: 'Supra dasturxoni, qadimiy vinochilik va tog‘ qishloqlari jamoaviy gastronomik tajriba yaratadi.',
    best: 'may–iyun, sentabr–oktabr', budget: 'low', style: ['wine', 'mountain', 'culture'],
    metrics: { H: 94, T: 53, X: 91, S: 79, A: 74, L: 92, D: 72 },
  },
  {
    code: 'BR', flag: '🇧🇷', name: 'Braziliya', region: 'Americas', capital: 'Brazilia', arrivals: 6.8,
    dishes: ['feijoada', 'churrasco', 'acarajé', 'açaí'],
    heritage: 'Amazon, Afrika va portugal ta’sirlarining bioxilma-xil uyg‘unligi',
    tourism: 'Rio, Salvador, Amazonka, Minas-Jerays va San-Paulu',
    story: 'Bioxilma-xillik, musiqa va ko‘cha madaniyati gastronomiyani festival va tabiat turizmi bilan birlashtiradi.',
    best: 'may–sentabr', budget: 'mid', style: ['nature', 'festival', 'street'],
    metrics: { H: 91, T: 50, X: 90, S: 68, A: 70, L: 88, D: 75 },
  },
  {
    code: 'AR', flag: '🇦🇷', name: 'Argentina', region: 'Americas', capital: 'Buenos-Ayres', arrivals: 6.2,
    dishes: ['asado', 'empanada', 'dulce de leche', 'Malbec'],
    heritage: 'Pampa chorvachiligi, parrilla va And sharobchilik madaniyati',
    tourism: 'Buenos-Ayres, Mendoza, Patagoniya, Salta va Iguasu',
    story: 'Go‘sht, vino va tango shahar hamda qishloq tajribalarini kuchli milliy narrativda birlashtiradi.',
    best: 'mart–may, sentabr–noyabr', budget: 'mid', style: ['wine', 'nature', 'urban'],
    metrics: { H: 88, T: 48, X: 88, S: 74, A: 73, L: 89, D: 72 },
  },
  {
    code: 'PE', flag: '🇵🇪', name: 'Peru', region: 'Americas', capital: 'Lima', arrivals: 3.3,
    dishes: ['ceviche', 'lomo saltado', 'ají de gallina', 'pachamanca'],
    heritage: 'Ceviche tayyorlash va iste’mol qilish amaliyoti — UNESCO merosi',
    tourism: 'Lima, Kusko, Machu-Pikchu, Arekipa va Amazonka',
    story: 'And mahsulotlari, Nikkei va Chifa ta’siri Peruni biologik hamda madaniy innovatsiya laboratoriyasiga aylantiradi.',
    best: 'may–sentabr', budget: 'mid', style: ['heritage', 'nature', 'innovation'],
    metrics: { H: 97, T: 42, X: 97, S: 78, A: 72, L: 93, D: 78 },
  },
];

export const metricMeta = [
  { key: 'H', short: 'Meros', full: 'Gastronomik meros va autentiklik', color: '#df6a3f' },
  { key: 'T', short: 'Talab', full: 'Turistik talab va bozor hajmi', color: '#d8a33d' },
  { key: 'X', short: 'Tajriba', full: 'Tajriba xilma-xilligi va sifati', color: '#377a70' },
  { key: 'S', short: 'Barqarorlik', full: 'Ekologik va ijtimoiy barqarorlik', color: '#7a7c44' },
  { key: 'A', short: 'Kirish', full: 'Transport va raqamli kirish imkoniyati', color: '#50708c' },
  { key: 'L', short: 'Mahalliy zanjir', full: 'Mahalliy qiymat zanjiri va jamoa ulushi', color: '#9b5745' },
  { key: 'D', short: 'Raqamli', full: 'Raqamli ko‘rinish va brend kuchi', color: '#725c8f' },
];

export const sources = [
  {
    type: 'Rasmiy statistika', year: '2026',
    title: 'UN Tourism World Tourism Barometer — 2025 yil yakuni',
    note: '1,52 mlrd xalqaro turist, mintaqaviy dinamika va turizm eksporti.',
    url: 'https://www.untourism.int/un-tourism-world-tourism-barometer-data',
  },
  {
    type: 'Rivojlanish statistikasi', year: '2026',
    title: 'World Bank Group — Tourism',
    note: '2024-yil: global YAIMga 10,9 trln dollar hissa, 357 mln ish o‘rni.',
    url: 'https://www.worldbank.org/ext/en/topic/tourism',
  },
  {
    type: 'Madaniy meros', year: '2025',
    title: 'UNESCO Creative Cities Network',
    note: '8 ijodiy yo‘nalishdagi 408 shahar va barqaror shahar rivoji modeli.',
    url: 'https://www.unesco.org/en/creative-cities',
  },
  {
    type: 'Indeks', year: '2024',
    title: 'WEF Travel & Tourism Development Index',
    note: '119 iqtisodiyotning turizm sharoiti, infratuzilmasi, resursi va barqarorligi.',
    url: 'https://www.weforum.org/publications/travel-tourism-development-index-2024/',
  },
  {
    type: 'Terminologiya', year: 'amaldagi',
    title: 'UN Tourism — Glossary of Tourism Terms',
    note: 'Gastronomik turizmning xalqaro institutsional ta’rifi.',
    url: 'https://www.unwto.org/glossary-tourism-terms',
  },
  {
    type: 'Ilmiy maqola', year: '2018',
    title: 'Ellis, Park, Kim & Yeoman — What is food tourism?',
    note: 'Motivatsiya, madaniyat, autentiklik, boshqaruv va destinatsiya yondashuvi.',
    url: 'https://doi.org/10.1016/j.tourman.2018.03.025',
  },
  {
    type: 'Ilmiy maqola', year: '2015',
    title: 'Richards — Evolving gastronomic experiences',
    note: 'Food → foodie → foodscape evolyutsion konsepsiyasi.',
    url: 'https://doi.org/10.3727/216929715X14298190828796',
  },
  {
    type: 'Ilmiy maqola', year: '2008',
    title: 'Everett & Aitchison — Food tourism and regional identity',
    note: 'Qishloq regeneratsiyasi, identitet va ishlab chiqaruvchi–iste’molchi aloqasi.',
    url: 'https://doi.org/10.2167/jost696.0',
  },
  {
    type: 'Barqarorlik', year: 'amaldagi',
    title: 'UN Tourism — Global Roadmap for Food Waste Reduction',
    note: 'Turizmda oziq-ovqat isrofini o‘lchash, oldini olish va qayta taqsimlash.',
    url: 'https://www.unwto.org/sustainable-development/food-waste-reduction-in-tourism',
  },
];
